name: project-prog-econ
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - alabaster=0.7.10
  - asn1crypto=0.24.0
  - attrs=17.4.0
  - babel=2.5.3
  - bleach=2.1.2
  - certifi=2018.1.18
  - chardet=3.0.4
  - colorama=0.3.9
  - cryptography=2.1.4
  - cycler=0.10.0
  - decorator=4.2.1
  - docutils=0.14
  - entrypoints=0.2.3
  - freetype=2.8
  - html5lib=1.0.1
  - idna=2.6
  - imagesize=1.0.0
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.2.1
  - ipython-notebook=4.0.4
  - ipython_genutils=0.2.0
  - jedi=0.11.1
  - jinja2=2.10
  - joblib=0.11
  - jsonschema=2.6.0
  - libpng=1.6.34
  - libsodium=1.0.15
  - libtiff=4.0.9
  - markupsafe=1.0
  - matplotlib=2.1.2
  - mistune=0.8.3
  - mkl=2018.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nose=1.3.7
  - notebook=5.4.0
  - numpy=1.14.1
  - openssl=1.0.2n
  - packaging=16.8
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.1.1
  - path.py=11.0
  - pickleshare=0.7.4
  - pip=9.0.1
  - pluggy=0.6.0
  - prompt_toolkit=1.0.15
  - py=1.5.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - pytest=3.4.2
  - python=3.5.4
  - python-dateutil=2.6.1
  - pytz=2018.3
  - pyzmq=16.0.3
  - qt=5.6.2
  - requests=2.18.4
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - send2trash=1.5.0
  - setuptools=38.5.1
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.5.1
  - sphinx_rtd_theme=0.2.4
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - sqlite=3.22.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=4.5.3
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.30.0
  - yaml=0.1.7
  - zeromq=4.2.2
  - zlib=1.2.11
  - pip:
    - cloud-sptheme==1.7
    - latexcodec==1.0.1
    - oset==0.1.3
    - pybtex==0.19
    - pybtex-docutils==0.2.1
    - pyyaml==3.12
    - sphinxcontrib-bibtex==0.3.3
