#! python


def build(ctx):
    ctx.recurse('data_management')
    ctx.recurse('analysis')
    ctx.recurse('analysis/main_simulation')
    ctx.recurse('final')
    ctx.recurse('final/main_simulation')
    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    ctx.add_group()
    #ctx.recurse('paper')
    #ctx.recurse('documentation')
