#! python

def build(ctx):

    ctx(
        features='tex',
        source='bagging_paper.tex',
        prompt=1,
        name='bagging_paper'
    )
    # Install to the project root.
    ctx.install_files(
        ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
        'bagging_paper.pdf'
    )
